del *.class
javac src/baza/ModelBaze.java
javac src/baza/RadSaBazom.java
javac src/gui/KonfiguracionaForma.java
javac src/gui/podesavanja/KonfiguracioniModelTabele.java
javac src/server/Server.java
javac src/server/ServerKontroler.java
javac src/server/ServerskaNit.java
javac src/so/GenerickaSistemskaOperacija.java
javac src/so/kompanija/DodajKompaniju.java
javac src/so/kompanija/VratiSveKompanije.java
javac src/so/kompanija/VratiSveKompanijePoID.java
javac src/so/korisnik/DodajKorisnika.java
javac src/so/korisnik/UlogujSe.java
javac src/so/korisnik/ValidirajKorisnickoIme.java
javac src/so/korisnik/VratiSveKorisnike.java
javac src/so/preparat/DodajPreparat.java
javac src/so/preparat/VratiSvePreparate.java
javac src/so/preparat/VratiSvePreparatePoID.java
javac src/so/raspored/DodajRaspored.java
javac src/so/raspored/DObrisiRasporedeTretmana.java
javac src/so/raspored/VratiSveRasporede.java
javac src/so/rezervacija/DodajRezervaciju.java
javac src/so/rezervacija/StampajRezervaciju.java
javac src/so/rezervacija/VratiSveRezervacije.java
javac src/so/tretman/DodajTretman.java
javac src/so/tretman/IzmeniTretman.java
javac src/so/tretman/ObrisiTretman.java
javac src/so/tretman/VratiSveTretmane.java
javac src/so/tretman/VratiTretmanePoID.java
javac src/so/tretmanpreparati/DodajPreparateTretmana.java
javac src/so/tretmanpreparati/ObrisiPreparateTretmana.java
javac src/so/tretmanpreparati/VratiSvePreparateTretmana.java
javac src/so/zaposleni/DodajZaposlenog.java
javac src/so/zaposleni/VratiSveZaposlene.java
javac src/so/zaposleni/VratiZaposlenePoID.java
java src/gui/KonfiguracionaForma
pause